import pptxgen from "pptxgenjs";

const COLORS = {
  primary: "2563EB",
  secondary: "0F172A",
  text: "334155",
  light: "F8FAFC",
  border: "E2E8F0",
  white: "FFFFFF",
  muted: "64748B",
};

export const generatePPT=async (data)=>
{
    const ppt=new pptxgen()

    ppt.layout="LAYOUT_WIDE"
    ppt.author="SexyAI"
    ppt.title=data.title
    ppt.subject=data.title
    ppt.company="SexyAI"
    // ppt.lang="en-US"
    ppt.theme={
        headFontFace:"Aptos",
        bodyFontFace:"Aptos",
        // lang:"en-US"

    }

    addCoverPage(ppt,data)

    data?.slides?.forEach((s,index) => {
        addContentSlide(
            ppt,
            s.title,
            s.points,
            s.visual,
            index+1,
            data.slides.length
        )
    });

    addThankyou(ppt)

    return ppt
}

 const addCoverPage=(ppt,data)=>
   {
    const slide=ppt.addSlide()
    slide.background={
        color:COLORS.primary
    }
    slide.addShape(ppt.ShapeType.rect,{
        x:0,
        y:0,
        w:13.33,
        h:0.18,
        fill:{
            color:"60A5FA"
        },
        line:{
            color:"60A5FA"
        }
    })

    slide.addText(data.title,{
        x:0.7,
        y:1.7,
        w:12,
        h:0.8,
        align:"center",
        color:COLORS.white,
        bold:true,
        fontSize:28,
    })

    slide.addText(data.subtitle,{
        x:1,
        y:2.8,
        w:11.5,
        h:0.4,
        align:"center",
        color:"DBEAFE",
        bold:true,
        fontSize:16,
    })

    slide.addText("Generated By SexyAI",{
        x:0,
        y:6.9,
        w:13.33,
        h:0.2,
        align:"center",
        color:"BFDBFE",
        fontSize:10,
    })
   }

//   function addContentSlide(ppt,title,points,page,total)
//     {
//         const slide=ppt.addSlide()
//         slide.background={
//         color:COLORS.white
//         }

//         slide.addText(title,{
//         x:0.6,
//         y:0.35,
//         w:10,
//         h:0.4,
//         align:"center",
//         color:COLORS.primary,
//         bold:true,
//         fontSize:24,
//        })

//         slide.addShape(ppt.ShapeType.line,{
//         x:0.6,
//         y:0.85,
//         w:12,
//         h:0,
//         line:{
//             color:COLORS.border,
//             width:1.2,
//         }
//        })

//        const visiblePoints=points.slice(0,6)

//        visiblePoints.forEach((point,index)=>{
//             const y=1.2 + index*0.75

//             slide.addShape(ppt.ShapeType.roundRect,{
//         x:0.7,
//         y,
//         w:12,
//         h:0.58,
//         fill:{
//             color: index % 2 ? "F8FAFC" : "EFF6FF"
//         },
//         line:{
//             color:COLORS.border,
//         },
//         radius: 0.08,

//        })

//         slide.addShape(ppt.ShapeType.ellipse,{
//         x:0.92,
//         y: y + 0.18,
//         w:0.12,
//         h:0.12,
//         fill:{
//             color:COLORS.primary,
//         },
//         line:{
//             color:COLORS.primary,
//         },
//        })

//        slide.addText(point,{
//         x: 1.2,
//         y: y + 0.08,
//         w:11,
//         h:0.35,
//         color:COLORS.text,
//         fit:"shrink",
//         fontSize:15,
//        })

//        slide.addText(`${page}/${total}`,{
//         x: 12.1,
//         y: 6.9,
//         w:0.8,
//         h:0.2,
//         align:"right",
//         color:COLORS.muted,
//         fontSize:10,
//        })

//        slide.addText(`SexyAI`,{
//         x: 0.6,
//         y: 6.9,
//         w:2,
//         h:0.2,
//         color:COLORS.muted,
//         fontSize:10,
//        })

//        })
//     }

function addContentSlide(ppt, title, points, visual, page, total) {
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.white
    };

    // =========================
    // TITLE
    // =========================
    slide.addText(title, {
        x: 0.6,
        y: 0.35,
        w: 12,
        h: 0.4,
        align: "center",
        color: COLORS.primary,
        bold: true,
        fontSize: 24,
    });

    // =========================
    // TITLE SEPARATOR
    // =========================
    slide.addShape(ppt.ShapeType.line, {
        x: 0.6,
        y: 0.85,
        w: 12,
        h: 0,
        line: {
            color: COLORS.border,
            width: 1.2,
        }
    });

    // =========================
    // CONTENT AREA
    // =========================
    const visiblePoints = points?.slice(0, 6) || [];

    // Left side width
    const contentX = 0.7;
    const contentW = visual?.type === "image" ? 7.0 : 12;

    visiblePoints.forEach((point, index) => {

        const y = 1.2 + index * 0.75;

        // Point background
        slide.addShape(ppt.ShapeType.roundRect, {
            x: contentX,
            y: y,
            w: contentW,
            h: 0.58,

            fill: {
                // FIXED: index instead of i
                color: index % 2 ? "F8FAFC" : "EFF6FF"
            },

            line: {
                color: COLORS.border,
                width: 0.8
            },

            radius: 0.08,
        });

        // Bullet
        slide.addShape(ppt.ShapeType.ellipse, {
            x: contentX + 0.22,
            y: y + 0.18,
            w: 0.12,
            h: 0.12,

            fill: {
                color: COLORS.primary,
            },

            line: {
                color: COLORS.primary,
            },
        });

        // Point text
        slide.addText(point, {
            x: contentX + 0.5,
            y: y + 0.08,
            w: contentW - 0.7,
            h: 0.35,

            color: COLORS.text,
            fit: "shrink",
            fontSize: 15,
            margin: 0,
        });
    });


    // =========================
    // VISUAL / IMAGE
    // =========================
    if (visual?.type === "image") {

        const imageX = 8.0;
        const imageY = 1.25;
        const imageW = 4.6;
        const imageH = 4.8;

        // Image container
        slide.addShape(ppt.ShapeType.roundRect, {
            x: imageX,
            y: imageY,
            w: imageW,
            h: imageH,

            fill: {
                color: "F8FAFC"
            },

            line: {
                color: COLORS.border,
                width: 1
            },

            radius: 0.08
        });


        // --------------------------------
        // ACTUAL IMAGE
        // --------------------------------

        if (visual.path) {

            slide.addImage({
                path: visual.path,

                x: imageX + 0.15,
                y: imageY + 0.15,
                w: imageW - 0.3,
                h: imageH - 0.3,

                sizingContain: true
            });

        } else if (visual.data) {

            slide.addImage({
                data: visual.data,

                x: imageX + 0.15,
                y: imageY + 0.15,
                w: imageW - 0.3,
                h: imageH - 0.3,

                sizingContain: true
            });

        } else {

            // --------------------------------
            // FALLBACK
            // --------------------------------

            slide.addText("Visual", {
                x: imageX + 0.2,
                y: imageY + 1.4,
                w: imageW - 0.4,
                h: 0.4,

                align: "center",
                color: COLORS.primary,
                bold: true,
                fontSize: 20,
            });

            slide.addText(
                visual.description || "Visual representation",
                {
                    x: imageX + 0.4,
                    y: imageY + 2.0,
                    w: imageW - 0.8,
                    h: 1.2,

                    align: "center",
                    valign: "mid",
                    color: COLORS.muted,
                    fontSize: 12,
                    fit: "shrink",
                    margin: 0.1,
                }
            );
        }
    }


    // =========================
    // FOOTER
    // =========================

    slide.addText(`${page}/${total}`, {
        x: 12.1,
        y: 6.9,
        w: 0.8,
        h: 0.2,

        align: "right",
        color: COLORS.muted,
        fontSize: 10,
    });

    slide.addText(`SexyAI`, {
        x: 0.6,
        y: 6.9,
        w: 2,
        h: 0.2,

        color: COLORS.muted,
        fontSize: 10,
    });
}

const addThankyou=(ppt)=>{
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.secondary
    };

    slide.addText(`THANK YOU`, {
        x: 0,
        y: 2.2,
        w: 13.33,
        h: 0.8,
        align:"center",
        color: COLORS.white,
        fontSize: 34,
        bold:true,
    });

     slide.addText(`Generated By SexyAI`, {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align:"center",
        color: "94A3B8",
        fontSize: 10,
    });
}

