
import fs from "fs/promises";
import os from "os";
import path from "path";

const TEMP_FILE_TTL = 30 * 1000; // 10 minutes

const TEMP_FILE_PREFIXES = [
    "pdf-",
    "ppt-",
    "image-"
];

export const s3Upload = async (filename, buffer, contentType) => {
    const tempDir = os.tmpdir();

    const safeFilename = path.basename(filename);
    const filePath = path.join(tempDir, safeFilename);

    await fs.writeFile(filePath, buffer);

    console.log(`Temporary file saved: ${filePath}`);

    return safeFilename;
};


// Automatically clean expired files
const cleanupTempFiles = async () => {
    try {
        const tempDir = os.tmpdir();

        const files = await fs.readdir(tempDir);

        for (const filename of files) {

            // Only touch files generated by our application
            const isOurFile = TEMP_FILE_PREFIXES.some(prefix =>
                filename.startsWith(prefix)
            );

            if (!isOurFile) {
                continue;
            }

            const filePath = path.join(tempDir, filename);

            try {
                const stats = await fs.stat(filePath);

                const fileAge = Date.now() - stats.mtimeMs;

                if (fileAge > TEMP_FILE_TTL) {
                    await fs.unlink(filePath);

                    console.log(
                        `Expired temporary file deleted: ${filename}`
                    );
                }

            } catch (error) {
                // File may have already been deleted
            }
        }

    } catch (error) {
        console.error("Temporary file cleanup error:", error);
    }
};


// Check every 1 minute
const cleanupInterval = setInterval(
    cleanupTempFiles,
    60 * 1000
);

// Don't keep Node process alive just because of this timer
cleanupInterval.unref();


// import { PutObjectCommand } from "@aws-sdk/client-s3"
// import {s3} from "../config/s3.js"
// export const s3Upload=async (filename,buffer,contentType)=>
// {   
//     //command to send data to s3 aws cloud service
//     await s3.send(
//         new PutObjectCommand({
//             Bucket:process.env.AWS_BUCKET_NAME,
//             Body:buffer,
//             Key:filename,
//             ContentType:contentType
//         })
//     )
//     return filename
// }